ceras:
  cors:
    allowed: ${CORS_ALLOWED_HOSTS}
  kafka:
    loggingTopic: ${LOGGING_TOPIC}
    consumer:
      logging:
        bootstrap: ${KAFKA_BOOTSTRAP_URL}
        topic: ${LOGGING_TOPIC}
        groupid: logging
        concurrent:
          requests: ${LOGGING_CONCURRENT_REQUEST:1}
  uniqueID: ${UNIQUE_ID}
spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      uri: mongodb://${MONGO_DB_HOST:localhost}/${MONGO_DB_NAME}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
  kafka:
    listener:
      concurrency: ${KAFKA_CONSUMER_CONCURRENCY:1}
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_SERVER}
      key-deserializer: '"org.apache.kafka.common.serialization.StringDeserializer"'
      value-deserializer: '"org.apache.kafka.common.serialization.StringDeserializer"'
logging:
  level:
    root: ERROR
    com.cerashealth.iamhome: ${LOG_LEVEL}
server:
  port : 8082